### PR TITLE
create accurate timer for metric flush

### PR DESCRIPTION
**Pull request by thomasmuehlschlegel**
clamp timestamp to a precise interval #459

### CODE REVIEW

**Comment by mrtazz** [comment]
Thank you for this patch. However there is still no explanation of why this is useful and why it can't be implemented in backends if they need it. And the issue you are referencing is closed. I'm happy to discuss this further on issue #459 if there is a need I'm overlooking here.

**Comment by thomasmuehlschlegel** [comment]
You are using setInterval() to flush the metrics periodically. But the problem with JavaScript timers is that they’re not very accurate. Thus you have a minimal delay which is escalating with every flush. When the delay overstep a whole second then no data will be available for the affected second which leads to undesired gaps in the graph. 
I observed that behaviour on my application every 10 minutes. I am wondering why nobody else is struggling. Maybe the delay is increasing further by the flushed data size or by a poor server. 

This patch fixes the appearance of that undesired gaps by using an accurate JavaScript timer and by clamping timestamp to a precise interval which leads to nice and continuous graphs.

(reference: http://www.sitepoint.com/creating-accurate-timers-in-javascript/)

**Comment by fessyfoo** [comment]
+1 for @thomasmuehlschlegel reason.  we have the same issue.  #513

**Comment by pathzzrd** [comment]
Merged via command line

**Pull request closed without merging**
