### PR TITLE
Upgrade hashring to 3.2 (pure js version)

### PR DESCRIPTION
**Pull request by hit9**
@mrtazz

### CODE REVIEW

**Comment by hit9** [comment]
The 3.1 version is not compatible with higher version of iojs.

**Comment by mrtazz** [comment]
does this supersede and also fix https://github.com/etsy/statsd/pull/533 ?

**Comment by mrtazz** [comment]
@hit9 any updates on this?

**Comment by mrtazz** [comment]
seems like it does fix the issue, thanks for the patch!

**Pull request merged**
