### PR TITLE
Allow the proxy to listen over TCP

### PR DESCRIPTION
**Pull request by tylernisonoff**
I'd like to eventually allow the proxy to send to its backends over tcp, but I felt it was fine for that to be a separate commit, since the proxy currently does not respect server configuration of the backends as it is.

### CODE REVIEW

**Comment by pathzzrd** [comment]
Thanks for the patch.

**Comment by tylernisonoff** [comment]
@pathzzrd  was this intentionally closed, or meant to be merged?

**Comment by pathzzrd** [comment]
@tylernisonoff 
This was manually merged via the commandline:
https://github.com/etsy/statsd/commit/0a20119ad8c75f81dde7916b3b25e56027f21ec3

**Comment by tylernisonoff** [comment]
@pathzzrd ah cool! Thanks

**Pull request closed without merging**
